# SPDX-FileCopyrightText: pydot contributors
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "pydot"
SPDX-PackageSupplier = "Łukasz <lukaszlapinski7@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/pydot/pydot"

[[annotations]]
path = ["test/graphs/**", "test/my_tests/**", "test/from-past-to-future/**", "test/graphs_disabled/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "pydot contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["src/pydot/_vendor/tempfile.py"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2001-2023 Python Software Foundation. All rights reserved."
SPDX-License-Identifier = "Python-2.0"

